#
#   Author: Rohith
#   Date: 2014-10-17 00:40:22 +0100 (Fri, 17 Oct 2014)
#
#  vim:ts=2:sw=2:et
#
FROM ubuntu
MAINTAINER <gambol99@gmail.com>
RUN apt-get update
RUN apt-get install -y openssh-server
EXPOSE 22
