---
default_options: &defaults
  box_name: cloud-ubuntu
  box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
  bootstrap:
    type: script
    script: ./boot/bootstrap.sh
  spec:

default_master_specs: &default_specs
  cpus: 1
  memory: 1024
  biosbootmenu: disabled

default_slave_specs: &default_slave_specs
  cpus: 2
  memory: 2048
  biosbootmenu: disabled

boxes:
  - <<: *defaults
    hostname: mesos-master101
    networks:
    - name: private_network
      ip: 10.0.1.100
    spec:
      <<: *default_specs
  - <<: *defaults
    hostname: mesos-master102
    networks:
    - name: private_network
      ip: 10.0.1.101
    spec:
      <<: *default_specs
  - <<: *defaults
    hostname: mesos-slave101
    networks:
    - name: private_network
      ip: 10.0.1.201
    spec:
      <<: *default_slave_specs
  - <<: *defaults
    hostname: mesos-slave102
    networks:
    - name: private_network
      ip: 10.0.1.202
    spec:
      <<: *default_slave_specs
  - <<: *defaults
    hostname: mesos-slave103
    networks:
    - name: private_network
      ip: 10.0.1.203
    spec:
      <<: *default_slave_specs
  - <<: *defaults
    hostname: mesos-slave104
    networks:
    - name: private_network
      ip: 10.0.1.204
    spec:
      <<: *default_slave_specs
  - <<: *defaults
    hostname: events101
    networks:
    - name: private_network
      ip: 10.0.1.111
    spec:
      <<: *default_specs
  - <<: *defaults
    hostname: hub101
    networks:
    - name: private_network
      ip: 10.0.1.112
    spec:
      <<: *default_specs

