---
- hostname: mesos-master101
  box_name: cloud-ubuntu
  box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
  bootstrap:
    type: script
    script: ./boot/bootstrap.sh
  networks:
  - name: private_network
    ip: 10.0.1.100
  spec:
    cpus: 1
    memory: 1024
    biosbootmenu: disabled
- hostname: mesos-master102
  box_name: cloud-ubuntu
  box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
  bootstrap:
    type: script
    script: ./boot/bootstrap.sh
  networks:
  - name: private_network
    ip: 10.0.1.101
  spec:
    cpus: 1
    memory: 1024
    biosbootmenu: disabled
- hostname: mesos-slave101
  box_name: cloud-ubuntu
  box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
  bootstrap:
    type: script
    script: ./boot/bootstrap.sh
  networks:
  - name: private_network
    ip: 10.0.1.201
  spec:
    cpus: 2
    memory: 2048
    biosbootmenu: disabled
- hostname: mesos-slave102
  box_name: cloud-ubuntu
  box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
  bootstrap:
    type: script
    script: ./boot/bootstrap.sh
  networks:
  - name: private_network
    ip: 10.0.1.202
  spec:
    cpus: 2
    memory: 2048
    biosbootmenu: disabled
- hostname: mesos-slave103
  box_name: cloud-ubuntu
  box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
  bootstrap:
    type: script
    script: ./boot/bootstrap.sh
  networks:
  - name: private_network
    ip: 10.0.1.203
  spec:
    cpus: 1
    memory: 2048
    biosbootmenu: disabled
- hostname: mesos-slave104
  box_name: cloud-ubuntu
  box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
  bootstrap:
    type: script
    script: ./boot/bootstrap.sh
  networks:
  - name: private_network
    ip: 10.0.1.204
  spec:
    cpus: 1
    memory: 2048
    biosbootmenu: disabled


