#
#   Author: Rohith (gambol99@gmail.com)
#   Date: 2014-10-09 17:47:17 +0100 (Thu, 09 Oct 2014)
#
#  vim:ts=2:sw=2:et
#
---
port: 2047
bind: '127.0.0.1'
exchange_username: tickets
exchange_password: password
exchange_hostname: 10.0.1.111
exchange_topic: stream
